tags:
- name: Auth
  description: Staff Savvy Backend APIs

paths:
# [GET] status
  /open/ping:
    get:
      tags:
      - open
      summary: Check the status of the server
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
# [POST] login
  /auth/login:
    post:
      summary: Logs in user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - password
            example:
              email: john.doe@example.com
              password: password123
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid email or password

# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
 - https
 - http
